# Generated by Django 4.0.4 on 2022-05-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='sponsor_id',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='student_id',
        ),
        migrations.AddField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.sponsor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='club.student'),
            preserve_default=False,
        ),
    ]
