# Generated by Django 4.0.4 on 2022-05-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_remove_donation_sponsor_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'verbose_name': 'Homiylik', 'verbose_name_plural': 'Homiyliklar'},
        ),
        migrations.AlterField(
            model_name='donation',
            name='sponsor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='club.sponsor'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='club.student'),
        ),
    ]
