# Generated by Django 4.0.4 on 2022-05-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_remove_donation_status_remove_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('Yangi', 'Yangi'), ('Moderatsiya', 'Moderatsiya'), ('Tasdiqlangan', 'Tasdiqlangan'), ('Bekor qilingan', 'Bekor qilingan')], default='Yangi', max_length=255),
        ),
    ]
